export interface Product {
  name: string;
  description: string;
  price: number;
  platform: string;
  /**
   * The URL of the product image, generated by the vision model.
   * This will be a data URL (base64 encoded).
   */
  imageUrl: string;
}

export interface EcommerceSource {
  platform: string;
  region: string;
  specialties: string[];
  url: string;
}

export interface ApiResponse {
  textResponse: string;
  products: Product[];
  ecommerceSources: EcommerceSource[];
}

// Type for the raw response from Gemini before image generation
export interface GeminiTextResponse {
  text_response: string;
  // FIX: Corrected the malformed type for `ecommerce_sources`. The original type caused a TypeScript error.
  ecommerce_sources: EcommerceSource[];
  products: (Omit<Product, 'imageUrl'> & { image_prompt: string })[];
}